lang = "Rust"
organization_id = "ginger-society"
dir = "."
spec_url = "/openapi.json"
service_type = "RPCEndpoint"

[services."@ginger-society/IAMService"]
prod = "https://api.gingersociety.org/iam"
prod_k8 = "http://iam-service-api-service/iam"
stage = "https://api.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"

[portals_refs]

[ws_refs."@ginger-society/IAMService"]
prod_k8 = ""
prod = ""
stage = ""
stage_k8 = ""

[urls]
prod = "https://api.gingersociety.org/presence"
stage_k8 = "http://ginger-presence-service/presence"
stage = "https://api.gingersociety.org/presence"
prod_k8 = "https://api.gingersociety.org/presence"
dev = "https://api.gingersociety.org/presence"

[urls_ws]
